services:
  core-pg:
    image: postgres:17
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pg
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: